{% set name = "treepoem" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15baba2cfcbe965cbc82827fcbc81a2726feaeb85e4f8c5d8837e4dc860275aa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - libpng
    - libffi
    - libjpeg-turbo
    - pillow

test:
  imports:
    - treepoem

about:
  home: https://github.com/adamchainz/treepoem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Barcode rendering for Python supporting QRcode, Aztec, PDF417, I25, Code128, Code39 and many more types.
  doc_url: https://github.com/adamchainz/treepoem
  dev_url: https://github.com/adamchainz/treepoem

extra:
  recipe-maintainers:
    - Ryan-Dmello
