{% set name = "treepoem" %}
{% set version = "3.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/treepoem-{{ version }}.tar.gz
  sha256: 824cf181a74955e9a909e71b8e8c79e495e2c78d6c7a5ced93ef5f821c254d73

build:
  number: 0
  noarch: python
  entry_points:
    - treepoem=treepoem.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pillow
    - ghostscript

test:
  imports:
    - treepoem
  commands:
    - pip check
    - treepoem --help
  requires:
    - pip

about:
  home: https://github.com/adamchainz/treepoem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Barcode rendering for Python supporting QRcode, Aztec, PDF417, I25, Code128, Code39 and many more types.
  doc_url: https://github.com/adamchainz/treepoem
  dev_url: https://github.com/adamchainz/treepoem

extra:
  recipe-maintainers:
    - Ryan-Dmello
