{% set name = "treepoem" %}
{% set version = "3.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/treepoem-{{ version }}.tar.gz
  sha256: 081b500a6c3dd6a231a89ea44d20c1685b94c23e93eb13a317cc00e0d549770f

build:
  number: 0
  noarch: python
  entry_points:
    - treepoem=treepoem.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pillow
    - ghostscript

test:
  imports:
    - treepoem
  commands:
    - pip check
    - treepoem --help
  requires:
    - pip

about:
  home: https://github.com/adamchainz/treepoem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Barcode rendering for Python supporting QRcode, Aztec, PDF417, I25, Code128, Code39 and many more types.
  doc_url: https://github.com/adamchainz/treepoem
  dev_url: https://github.com/adamchainz/treepoem

extra:
  recipe-maintainers:
    - Ryan-Dmello
